/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nezet;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modell.Harcos;
import modell.Palya;
import modell.Varazslo;

/**
 *
 * @author dan
 */
public class HEsVGUI extends javax.swing.JFrame {

    /**
     * Creates new form HEsVGUI
     */
    public static final String LEIRAS="Egy adott játéktérben mozoghat a Harcos és a Varázsló. "
            + "Ha ugyanarra a mezőre lépnek, akkor harcolnak. Akár harcolnak, akár nem, minden "
            + "körben változtatják a pozíciójukat. Ha ugyanoda léptek, tehát harcolnak, akkor mindkettő "
            + "fél sebez a másikba. A játék addig tart, ameddig legalább az egyik játékos el nem veszíti "
            + "az életerejét.";
    
    private final Icon HARCOS = new ImageIcon(getClass().getResource("/kepek/harcos80x75.jpg"));
    private final Icon VARAZSLO = new ImageIcon(getClass().getResource("/kepek/varazslo80x75.jpg"));
    private final Icon HARC = new ImageIcon(getClass().getResource("/kepek/harc80x75.jpg"));
    private final Icon URES = new ImageIcon(getClass().getResource("/kepek/ures.jpg"));
    
    private Harcos h;
    private Varazslo v;
    private Palya p;
    
    private JLabel[] lblMezok;
    
    public HEsVGUI() {
        initComponents();
        
        init();      
        
        pack();
        
    }
    
    private void alaphelyzet(){
        btnUjra.setEnabled(false);
        lblLeiras.setText("<html><p style='padding=10px'>"+LEIRAS+"</p></html>");
        palyaTisztit();
    }
    
    private void alapPoz(){
        p.setMezo(h.getPozicio(), 'H');
        p.setMezo(v.getPozicio(), 'V');
        
        lblMezok[h.getPozicio()].setIcon(HARCOS);
        lblMezok[v.getPozicio()].setIcon(VARAZSLO);
    }
    
    private void ujPoz() {
        h.setPozicio();
        v.setPozicio();
        p.setMezo(h.getPozicio(), 'H');
        p.setMezo(v.getPozicio(), 'V');
        
        lblMezok[h.getPozicio()].setIcon(HARCOS);
        lblMezok[v.getPozicio()].setIcon(VARAZSLO);
    }
    
    private void palyaTisztit() {
        for (int i = 0; i < Palya.PALYA_HOSSZ; i++) {
            lblMezok[i].setIcon(URES);
        }
    }

    private void vanEHarc() {
        if (h.getPozicio()==v.getPozicio()) {            
            String visszaj="";
            int vSebzes=v.getSebzes();
            int hSebzes=h.getSebzes();
            
            h.setEletero(h.getEletero()-vSebzes);
            v.setEletero(v.getEletero()-hSebzes);
            
            lblMezok[h.getPozicio()].setIcon(HARC);
            
            visszaj+="<html>";
            visszaj+="<h2>Harc!</h2>";
            visszaj+="<p>Harcos vesztett: "+vSebzes+" életerőt! Jelenlegi életereje: "+h.getEletero()+"<br>";
            visszaj+="Varázsló vesztett: "+hSebzes+" életerőt! Jelenlegi életereje: "+v.getEletero()+"<br></p>";
            visszaj+="</html>";
            lblVisszajelzes.setText(visszaj);
        }else{
            lblVisszajelzes.setText("<html><h2>Nincs harc!</h2></html>");
        }
    }
    
    private void init(){
        this.lblMezok = new JLabel[]{lblMezo1, lblMezo2, lblMezo3};
        this.p=new Palya();
        this.h=new Harcos();
        this.v=new Varazslo();
        
        alaphelyzet();        
        alapPoz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        btnUjra = new javax.swing.JButton();
        pnlLeiras = new javax.swing.JPanel();
        lblLeiras = new javax.swing.JLabel();
        pnlVisszajelzes = new javax.swing.JPanel();
        lblVisszajelzes = new javax.swing.JLabel();
        btnKovLep = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblMezo2 = new javax.swing.JLabel();
        lblMezo3 = new javax.swing.JLabel();
        lblMezo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Harcos és Varázsló");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlContainer.setLayout(new java.awt.GridLayout());

        btnUjra.setText("Újrakezdés");
        btnUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjraActionPerformed(evt);
            }
        });

        pnlLeiras.setBorder(javax.swing.BorderFactory.createTitledBorder("Leírás"));

        javax.swing.GroupLayout pnlLeirasLayout = new javax.swing.GroupLayout(pnlLeiras);
        pnlLeiras.setLayout(pnlLeirasLayout);
        pnlLeirasLayout.setHorizontalGroup(
            pnlLeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeirasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLeiras, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLeirasLayout.setVerticalGroup(
            pnlLeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeirasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLeiras, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlVisszajelzes.setBorder(javax.swing.BorderFactory.createTitledBorder("Visszajelzés"));

        javax.swing.GroupLayout pnlVisszajelzesLayout = new javax.swing.GroupLayout(pnlVisszajelzes);
        pnlVisszajelzes.setLayout(pnlVisszajelzesLayout);
        pnlVisszajelzesLayout.setHorizontalGroup(
            pnlVisszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisszajelzesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVisszajelzesLayout.setVerticalGroup(
            pnlVisszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVisszajelzesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnKovLep.setText("Következő lépés");
        btnKovLep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKovLepActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Mező"), "Mezők"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMezo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(lblMezo2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblMezo3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMezo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMezo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMezo3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLeiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlVisszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKovLep, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLeiras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlVisszajelzes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKovLep, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKovLepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKovLepActionPerformed
        palyaTisztit();
        ujPoz();
        vanEHarc();
        
        if (h.getEletero()<=0 || v.getEletero()<=0) {
            btnKovLep.setEnabled(false);
            btnUjra.setEnabled(true);
            if (h.getEletero()>v.getEletero()) {
                lblVisszajelzes.setText("<html><h2>Harcos nyert!</h2></html>");
            }else if(v.getEletero()>h.getEletero()){
                lblVisszajelzes.setText("<html><h2>Varázsló nyert!</h2></html>");
            }else{
                lblVisszajelzes.setText("<html><h2>Döntetlen!</h2></html>");
            }
        }
    }//GEN-LAST:event_btnKovLepActionPerformed

    private void btnUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjraActionPerformed
        init();
        btnKovLep.setEnabled(true);
        lblVisszajelzes.setText("");
    }//GEN-LAST:event_btnUjraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HEsVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HEsVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HEsVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HEsVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKovLep;
    private javax.swing.JButton btnUjra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLeiras;
    private javax.swing.JLabel lblMezo1;
    private javax.swing.JLabel lblMezo2;
    private javax.swing.JLabel lblMezo3;
    private javax.swing.JLabel lblVisszajelzes;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlLeiras;
    private javax.swing.JPanel pnlVisszajelzes;
    // End of variables declaration//GEN-END:variables
}
